version: '3.8'


services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000" 
    image: akshat1701/animal-movement-frontend
    depends_on:
      - db
      - backend
      

  backend:
    container_name: flask_backend
    build: ./
    ports:
      - "8000:8000" 
    image: akshat1701/animal-movement-backend
    # depends_on:
    #   - db

  db:
    image: postgres:16
    container_name: flask_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=animal-movement
    ports:
      - "5431:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 